# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1

orbs:
  publish-docs: infinitered/publish-docs@0.4


parameters:
  "force-docs":
    type: boolean
    default: false

defaults: &defaults
  docker: # Choose the version of Node you want here
    - image: cimg/node:18.17.1
  working_directory: ~/repo

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install React Native CLI and Ignite CLI
          command: |
            sudo npm i -g ignite-cli react-native-cli
      - run:
          name: Run tests
          command: yarn ci:test # this command will be added to/found in your package.json scripts

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Run semantic-release after all the above is set.
      - run:
          name: Publish to NPM
          command: yarn ci:publish # this will be added to your package.json scripts

# Parameters for the publish-docs orb
publish-details: &publish-details
  description: A delightful toolkit for building Node-based CLIs in TS/JS
  git_email: ci@infinite.red
  git_username: Infinite Red CI
  label: Gluegun
  project_name: gluegun
  source_docs_dir: ir-docs
  source_repo_directory: source
  target_docs_dir: docs
  target_repo: git@github.com:infinitered/ir-docs.git
  target_repo_directory: target

workflows:
  version: 2
  test_and_release:
    when:
      and:
        - not: << pipeline.parameters.force-docs >>
        - true  # Placeholder for correct YAML structure
    jobs:
      - setup
      - tests:
          requires:
            - setup
      - publish:
          requires:
            - tests
          filters:
            branches:
              only: master
  # for testing and debugging
  force-docs:
    when: << pipeline.parameters.force-docs >>
    jobs:
      - publish-docs/publish_docs:
          <<: *publish-details
#  test_docs:
#    when:
#      and:
#        - not: << pipeline.parameters.force-docs >>
#        - true  # Placeholder for correct YAML structure
#    jobs:
#      - publish-docs/build_docs:
#          <<: *publish-details
#          filters:
#            branches:
#              ignore:
#                - main
  publish_docs:
    when:
      and:
        - not: << pipeline.parameters.force-docs >>
        - true  # Placeholder for correct YAML structure
    jobs:
      - publish-docs/publish_docs:
          <<: *publish-details
          filters:
            branches:
              only:
                - ir-docs
          requires:
            - test_and_release
